name: heidi
description: A new Flutter project.
version: 1.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ### Update
  upgrader: ^8.4.0

  ### Logging
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  cupertino_icons: ^1.0.2
  sentry_flutter: ^7.13.2

  ### l10n
  intl: ^0.18.0

  ### State Management
  bloc: 8.1.0
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  provider: ^6.0.1

  ### Data
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.12
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  ### Networking
  dio: ^4.0.6
  retrofit: ^3.3.1
  http_parser: ^4.0.2
  http: ^0.13.3

  ### Code Generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0


  ### Device Permission
  device_info: 2.0.3
  permission_handler: 10.4.1
  url_launcher: 6.1.12
  connectivity: ^3.0.6

  ### Location
  location: 4.4.0

  ### ui
  flutter_svprogresshud: 1.0.0
  shimmer: 2.0.0
  dotted_border: 2.0.0+3
  font_awesome_flutter: 10.2.1
  card_swiper: 2.0.4
  cached_network_image: 3.2.3
  flutter_html: ^3.0.0-beta.1
  photo_view: ^0.14.0

#  webview_flutter: ^4.2.2
  flutter_widget_from_html: ^0.10.3

  ### File Reading
  open_filex: 4.3.1
  image_picker: 0.8.6
  flutter_slidable: ^3.0.0
  file_picker: ^5.5.0
  flutter_pdfview: ^1.0.1
  flutter_cached_pdfview: ^0.4.2
  flutter_cache_manager: ^3.3.1
  comment_box: ^0.0.18
  comment_tree: ^0.3.0
  path_provider: ^2.0.9
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  retrofit_generator: ^4.2.0

  freezed: ^2.3.2
  json_serializable: ^6.6.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:
  assets:
    - assets/images/
    - assets/locale/
    - assets/data/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Black.otf
        - asset: assets/fonts/ProximaNova-Bold.otf
        - asset: assets/fonts/ProximaNova-Extrabld.otf
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/ProximaNovaT-Thin.otf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-BlackItalic.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-BoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway-ExtraLightItalic.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-LightItalic.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-MediumItalic.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway-ThinItalic.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Black.ttf
        - asset: assets/fonts/Merriweather-BlackItalic.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather-BoldItalic.ttf
        - asset: assets/fonts/Merriweather-Italic.ttf
        - asset: assets/fonts/Merriweather-Light.ttf
        - asset: assets/fonts/Merriweather-LightItalic.ttf
        - asset: assets/fonts/Merriweather-Regular.ttf
  uses-material-design: true

